services:
  postgres:
    image: postgres:16-alpine
    container_name: kumpulink_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: kumpulink
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: kumpulink_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
