ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "domains" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "links" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tags" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "link_tags" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "_prisma_migrations" ENABLE ROW LEVEL SECURITY;
